# Generated by Django 6.0.7 on 2026-07-31 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderlineitem',
            name='ordered_boxes',
            field=models.PositiveIntegerField(blank=True, help_text='Number of boxes ordered.', null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderlineitem',
            name='pieces_per_box',
            field=models.PositiveIntegerField(blank=True, help_text='Pieces in each box. Auto-filled from product if available.', null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorderlineitem',
            name='ordered_qty',
            field=models.DecimalField(decimal_places=3, help_text='Total pieces ordered. Auto-calculated if boxes are entered.', max_digits=12),
        ),
    ]
