# Generated by Django 6.0.7 on 2026-08-02 16:03

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=160, verbose_name='Customer Name')),
                ('customer_phone', models.CharField(max_length=40, verbose_name='Phone Number')),
                ('customer_address', models.TextField(verbose_name='Customer Address / Location')),
                ('service_type', models.CharField(choices=[('INSTALLATION', 'New Unit Installation'), ('REPAIR', 'Repair & Maintenance'), ('FILTER_CHANGE', 'Filter Replacement'), ('INSPECTION', 'Inspection / Checkup'), ('OTHER', 'Other Service')], default='REPAIR', max_length=40, verbose_name='Service Required')),
                ('issue_description', models.TextField(verbose_name='Issue / Service Request Details')),
                ('scheduled_time', models.DateTimeField(blank=True, null=True, verbose_name='Scheduled Visit Date & Time')),
                ('assigned_technician', models.CharField(blank=True, max_length=120, verbose_name='Assigned Representative / Service Man')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=30)),
                ('service_charges', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Service Charges (PKR)')),
                ('notes', models.TextField(blank=True, verbose_name='Internal Notes / Resolution Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
