# Generated by Django 6.0.7 on 2026-08-02 18:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceticket',
            name='assigned_technician',
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='parts_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total Parts Price (PKR)'),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='parts_description',
            field=models.TextField(blank=True, verbose_name='Parts Changed / Replaced'),
        ),
        migrations.AlterField(
            model_name='serviceticket',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Resolution Note / Completion Remarks'),
        ),
        migrations.AlterField(
            model_name='serviceticket',
            name='service_charges',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Labor Service Fee (PKR)'),
        ),
        migrations.AlterField(
            model_name='serviceticket',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=30),
        ),
    ]
