# Generated by Django 6.0.7 on 2026-08-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_remove_serviceticket_assigned_technician_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceticket',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True, verbose_name='Scheduled Visit Date'),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='serviceman_name',
            field=models.CharField(blank=True, max_length=160, verbose_name='Serviceman / Technician Name'),
        ),
        migrations.AlterField(
            model_name='serviceticket',
            name='scheduled_time',
            field=models.DateField(blank=True, null=True, verbose_name='Scheduled Visit Date'),
        ),
    ]
