# Generated by Django 6.0.7 on 2026-07-29 19:40

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('origin_label', models.CharField(max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('sku', models.CharField(blank=True, max_length=64, unique=True)),
                ('configuration', models.CharField(choices=[('SINGLE', 'Single'), ('DUAL', 'Dual'), ('TRIPLE', 'Triple'), ('N_A', 'N/A')], default='N_A', max_length=20)),
                ('stage_count', models.PositiveIntegerField(blank=True, null=True)),
                ('unit_type', models.CharField(choices=[('FINISHED_UNIT', 'Finished Unit'), ('COMPONENT', 'Component'), ('SPARE_PART', 'Spare Part')], max_length=30)),
                ('unit_of_measure', models.CharField(default='piece', max_length=40)),
                ('reorder_level', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('cost_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('allow_negative_stock', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in_products', to='catalog.product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_of_materials', to='catalog.product')),
            ],
            options={
                'ordering': ['product__name', 'component__name'],
                'unique_together': {('product', 'component')},
            },
        ),
    ]
