# Generated by Django 6.0.7 on 2026-07-31 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pieces_per_box',
            field=models.PositiveIntegerField(blank=True, help_text='Number of pieces in one standard box. Leave blank if not applicable.', null=True),
        ),
    ]
